import Quickshell
import Quickshell.Io
import Quickshell.Services.Greetd
import QtQuick

// ===== GREETER BACKEND =====
// Wraps Quickshell's native Quickshell.Services.Greetd (confirmed real
// against this system's installed quickshell-0.3.0, matching the
// reference doc's API almost exactly: createSession/respond/launch,
// authMessage/authFailure/readyToLaunch). Same "backend exposes a small
// interface, UI never touches the auth system directly" shape as
// lock/backends/AuthBackend.qml (PamContext), just a different real
// backend underneath.
//
// `mock` auto-enables whenever `Greetd.available` is false -- i.e. always,
// when this is launched by hand outside of an actual greetd session (see
// greeter-shell.qml) -- so the whole UI can be built and screenshot-
// verified in a normal window before any NixOS module/greetd wiring
// exists at all, matching this project's own established "hardcoded UI
// first, then real logic" convention (same real/dev split already used
// for the lock screen, just here there's only ever one surface type since
// a greeter has no analogous "real session lock protocol" to gate behind
// a flag).
//
// users/sessions load from /etc/qs-greeter/{users,sessions}.json (real
// data, generated by modules/greeter.nix from config.users.users and the
// real wayland-sessions/*.desktop files) when present, falling back to
// the hardcoded demo data below when they're not -- which is always, when
// this is run by hand for windowed preview (greeter-shell.qml) on a
// machine that hasn't switched the module in, same absolute-path FileView
// convention PowerDropdown.qml's brightness file already uses in this
// project (not a relative path -- Quickshell's own config-root sandboxing
// makes relative-path FileView resolution from a copied/rooted config
// chancy, and there's no existing precedent for it in this codebase).
Item {
  id: root

  readonly property bool mock: !Greetd.available

  property var users: []           // [{name, init}]
  property int selectedUserIndex: 0
  property var sessions: []        // [{id, name, exec}]
  property int selectedSessionIndex: 0

  property bool busy: false
  property var msg: null           // {icon, text, color}, same shape Lock.qml uses
  signal launchRequested()

  readonly property var demoUsers: [
    { name: "joelsgc", init: "J" },
  ]
  readonly property var demoSessions: [
    { id: "hyprland", name: "Hyprland", exec: "Hyprland", desktopNames: "Hyprland" },
    { id: "plasma", name: "Plasma (Wayland)", exec: "startplasma-wayland", desktopNames: "KDE" },
  ]
  Component.onCompleted: {
    users = demoUsers;
    sessions = demoSessions;
    checkEnrollment();
  }

  FileView {
    path: "/etc/qs-greeter/users.json"
    onLoaded: {
      try {
        const parsed = JSON.parse(text());
        if (parsed.length > 0) {
          root.users = parsed.map(u => ({
            name: u.name,
            init: (u.displayName || u.name).charAt(0).toUpperCase(),
          }));
        }
      } catch (e) {
        console.warn("GreeterBackend: malformed users.json, keeping demo data:", e);
      }
    }
    onLoadFailed: (error) => {} // file doesn't exist yet (dev preview) -- keep demo data
  }
  FileView {
    path: "/etc/qs-greeter/sessions.json"
    onLoaded: {
      try {
        const parsed = JSON.parse(text());
        if (parsed.length > 0) {
          root.sessions = parsed;
          // Default to plain "hyprland", not whatever sorts first --
          // confirmed live that "hyprland-uwsm.desktop" sorts before
          // "hyprland.desktop" alphabetically ('-' < '.' in ASCII) in
          // the shell glob modules/greeter.nix builds this list from,
          // which silently made the uwsm-managed session the default.
          const i = parsed.findIndex(s => s.id === "hyprland");
          if (i !== -1) root.selectedSessionIndex = i;
        }
      } catch (e) {
        console.warn("GreeterBackend: malformed sessions.json, keeping demo data:", e);
      }
    }
    onLoadFailed: (error) => {} // file doesn't exist yet (dev preview) -- keep demo data
  }

  readonly property string selectedUser: users.length > 0 ? users[selectedUserIndex].name : ""
  property string _pendingPw: ""

  function pickUser(i) { selectedUserIndex = i; }
  function sessionStep(delta) {
    selectedSessionIndex = (selectedSessionIndex + delta + sessions.length) % sessions.length;
  }

  // ----- fingerprint enrollment, per selected user -----
  // Same fprintd-list check AuthBackend.qml (the lock screen) already
  // uses, re-run whenever the selected account changes -- unlike the
  // lock screen, the greeter can switch between several real accounts,
  // so "is fingerprint available" isn't fixed for the whole session.
  property string enrollListText: ""
  readonly property bool fingerprintEnrolled: !root.mock && root.enrollListText.indexOf(" - #") !== -1
  Process {
    id: enrollProc
    command: ["fprintd-list", root.selectedUser]
    stdout: StdioCollector {
      onStreamFinished: root.enrollListText = text
    }
  }
  function checkEnrollment() {
    if (root.mock || root.selectedUser === "") return;
    enrollProc.running = false;
    enrollProc.running = true;
  }
  onSelectedUserChanged: checkEnrollment()

  function submit(pw) {
    if (busy) return;
    busy = true;
    msg = null;
    _pendingPw = pw;
    if (mock) { mockTimer.restart(); return; }
    Greetd.createSession(selectedUser);
  }

  // fprintd is listed `sufficient`-and-first in the greetd PAM stack
  // (modules/greeter.nix), so a successful fingerprint scan alone
  // completes auth; a failed/timed-out scan falls through to pam_unix's
  // own password prompt, which is what `responseRequired` below answers.
  // Only one such prompt is expected per attempt for this stack.
  Connections {
    target: Greetd
    enabled: !root.mock
    function onAuthMessage(message, error, responseRequired, echoResponse) {
      if (responseRequired) {
        Greetd.respond(root._pendingPw);
        root._pendingPw = "";
      } else if (message) {
        root.msg = { icon: error ? "x" : "info", text: message, color: error ? "#ef596f" : "#5c6370" };
      }
    }
    function onAuthFailure(message) {
      root.busy = false;
      root.msg = { icon: "x", text: message || "authentication failed", color: "#ef596f" };
    }
    function onError(err) {
      root.busy = false;
      root.msg = { icon: "x", text: "greeter backend error: " + err, color: "#ef596f" };
    }
    function onReadyToLaunch() { root.launchRequested(); }
  }

  function doLaunch() {
    const s = sessions[selectedSessionIndex];
    if (mock) {
      console.log("MOCK launch:", s.exec);
      busy = false;
      return;
    }
    // XDG_CURRENT_DESKTOP set from the session's own real DesktopNames=
    // value (e.g. "KDE" for Plasma, "Hyprland" for Hyprland), not our own
    // filename-derived s.id -- portals, Qt platform theming and KDE
    // component detection all key off the real value. PATH is explicit
    // since Greetd.launch() doesn't inherit a normal login shell's PATH,
    // and session scripts that exec bare command names (not full store
    // paths) need it to find them. stdout/stderr redirected to a log file
    // so a session's own startup logging doesn't flash on the bare
    // console during the cage-to-session VT handoff.
    const envArgs = [
      "XDG_SESSION_TYPE=wayland",
      "XDG_SESSION_DESKTOP=" + s.id,
      "XDG_CURRENT_DESKTOP=" + (s.desktopNames || s.id),
      "PATH=/run/current-system/sw/bin",
    ];

    if (s.exec.indexOf("dbus-run-session") === -1) {
      // Hyprland (and anything else not needing the Plasma-specific
      // fixups below) -- left completely untouched, still the exact
      // short inline -c string confirmed working on real hardware.
      Greetd.launch(["/bin/sh", "-c",
        s.exec.trim() + " >/tmp/qs-greeter-session.log 2>&1"], envArgs);
      return;
    }

    // Plasma: write the real launch script to a file first, then tell
    // Greetd.launch() to run just that short file path -- confirmed live
    // (a phone video of the real console during a failed attempt) that
    // the previous approach, one long inline `/bin/sh -c "<giant
    // string>"` argument (export DBUS_SESSION_BUS_ADDRESS + sleep 5 +
    // the real exec + redirect, ~3x longer than Hyprland's always-working
    // one-liner), never actually ran: the console showed NixOS's normal
    // environment setup finish, then sat on a bare, blinking interactive
    // /bin/sh prompt -- i.e. /bin/sh started with no script/argument at
    // all, meaning the long command string was getting lost somewhere
    // between here and the shell actually executing, not failing inside
    // whatever it would have run. A short, fixed-size argv regardless of
    // which session is picked sidesteps that entirely.
    //
    // DBUS_SESSION_BUS_ADDRESS: plasma-dbus-run-session-if-needed spawns
    // its own private bus when this is unset, which fails immediately on
    // this system (/etc/dbus-1/session.conf is dbus's own deprecated
    // empty stub) -- pointing it at the systemd-user bus Hyprland's own
    // D-Bus clients already fall back to sidesteps that spawn entirely.
    // sleep: the same cage/kwin DRM-master handoff race this project
    // already fixed once for cage's own startup (a sleep 1 before
    // quickshell connects). The earlier "5s" value here was never
    // actually validated -- the whole command wasn't executing at all
    // until the script-file fix above -- so this is back to 1s, matching
    // cage's own fix, to see if that's actually sufficient now that the
    // real launch path works.
    const scriptContent =
      "#!/bin/sh\n" +
      "export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus\n" +
      "sleep 1\n" +
      "exec " + s.exec.trim() + " >/tmp/qs-greeter-session.log 2>&1\n";
    const safeScript = scriptContent.replace(/'/g, "'\\''");
    launchScriptWriterComponent.createObject(root, {
      command: ["/bin/sh", "-c",
        "printf '%s' '" + safeScript + "' > /tmp/qs-greeter-launch.sh && chmod +x /tmp/qs-greeter-launch.sh"],
      running: true,
      _launchEnv: envArgs,
    });
  }

  // Writes the launch script, then (only once that write process has
  // actually exited, so the file is guaranteed complete) runs it via
  // Greetd.launch() with just its short path -- see doLaunch()'s own
  // comment for why this two-step indirection replaced a single long
  // inline command string.
  Component {
    id: launchScriptWriterComponent
    Process {
      property var _launchEnv: []
      stdout: StdioCollector {}
      onExited: {
        Greetd.launch(["/bin/sh", "/tmp/qs-greeter-launch.sh"], _launchEnv);
        destroy();
      }
    }
  }

  // Mock auth: "test" succeeds, anything else fails -- mirrors the
  // reference doc's own mock-mode convention.
  Timer {
    id: mockTimer
    interval: 500
    onTriggered: {
      if (root._pendingPw === "test") {
        root._pendingPw = "";
        root.launchRequested();
      } else {
        root._pendingPw = "";
        root.busy = false;
        root.msg = { icon: "x", text: "wrong password (mock: use 'test')", color: "#ef596f" };
      }
    }
  }
}
