import Quickshell
import Quickshell.Io
import Quickshell.Services.Greetd
import QtQuick

// ===== GREETER BACKEND =====
// Wraps Quickshell's native Quickshell.Services.Greetd (confirmed real
// against this system's installed quickshell-0.3.0, matching the
// reference doc's API almost exactly: createSession/respond/launch,
// authMessage/authFailure/readyToLaunch). Same "backend exposes a small
// interface, UI never touches the auth system directly" shape as
// lock/backends/AuthBackend.qml (PamContext), just a different real
// backend underneath.
//
// `mock` auto-enables whenever `Greetd.available` is false -- i.e. always,
// when this is launched by hand outside of an actual greetd session (see
// greeter-shell.qml) -- so the whole UI can be built and screenshot-
// verified in a normal window before any NixOS module/greetd wiring
// exists at all, matching this project's own established "hardcoded UI
// first, then real logic" convention (same real/dev split already used
// for the lock screen, just here there's only ever one surface type since
// a greeter has no analogous "real session lock protocol" to gate behind
// a flag).
//
// users/sessions load from /etc/qs-greeter/{users,sessions}.json (real
// data, generated by modules/greeter.nix from config.users.users and the
// real wayland-sessions/*.desktop files) when present, falling back to
// the hardcoded demo data below when they're not -- which is always, when
// this is run by hand for windowed preview (greeter-shell.qml) on a
// machine that hasn't switched the module in, same absolute-path FileView
// convention PowerDropdown.qml's brightness file already uses in this
// project (not a relative path -- Quickshell's own config-root sandboxing
// makes relative-path FileView resolution from a copied/rooted config
// chancy, and there's no existing precedent for it in this codebase).
Item {
  id: root

  readonly property bool mock: !Greetd.available

  property var users: []           // [{name, init}]
  property int selectedUserIndex: 0
  property var sessions: []        // [{id, name, exec}]
  property int selectedSessionIndex: 0

  property bool busy: false
  property var msg: null           // {icon, text, color}, same shape Lock.qml uses
  signal launchRequested()

  readonly property var demoUsers: [
    { name: "joelsgc", init: "J" },
  ]
  readonly property var demoSessions: [
    { id: "hyprland", name: "Hyprland", exec: "Hyprland" },
    { id: "plasma", name: "Plasma (Wayland)", exec: "startplasma-wayland" },
  ]
  Component.onCompleted: {
    users = demoUsers;
    sessions = demoSessions;
  }

  FileView {
    path: "/etc/qs-greeter/users.json"
    onLoaded: {
      try {
        const parsed = JSON.parse(text());
        if (parsed.length > 0) {
          root.users = parsed.map(u => ({
            name: u.name,
            init: (u.displayName || u.name).charAt(0).toUpperCase(),
          }));
        }
      } catch (e) {
        console.warn("GreeterBackend: malformed users.json, keeping demo data:", e);
      }
    }
    onLoadFailed: (error) => {} // file doesn't exist yet (dev preview) -- keep demo data
  }
  FileView {
    path: "/etc/qs-greeter/sessions.json"
    onLoaded: {
      try {
        const parsed = JSON.parse(text());
        if (parsed.length > 0) {
          root.sessions = parsed;
          // Default to plain "hyprland", not whatever sorts first --
          // confirmed live that "hyprland-uwsm.desktop" sorts before
          // "hyprland.desktop" alphabetically ('-' < '.' in ASCII) in
          // the shell glob modules/greeter.nix builds this list from,
          // which silently made the uwsm-managed session the default.
          const i = parsed.findIndex(s => s.id === "hyprland");
          if (i !== -1) root.selectedSessionIndex = i;
        }
      } catch (e) {
        console.warn("GreeterBackend: malformed sessions.json, keeping demo data:", e);
      }
    }
    onLoadFailed: (error) => {} // file doesn't exist yet (dev preview) -- keep demo data
  }

  readonly property string selectedUser: users.length > 0 ? users[selectedUserIndex].name : ""
  property string _pendingPw: ""

  function pickUser(i) { selectedUserIndex = i; }
  function sessionStep(delta) {
    selectedSessionIndex = (selectedSessionIndex + delta + sessions.length) % sessions.length;
  }

  function submit(pw) {
    if (busy) return;
    busy = true;
    msg = null;
    _pendingPw = pw;
    if (mock) { mockTimer.restart(); return; }
    Greetd.createSession(selectedUser);
  }

  Connections {
    target: Greetd
    enabled: !root.mock
    function onAuthMessage(message, error, responseRequired, echoResponse) {
      if (responseRequired) {
        // First (and, for this stack, only expected) secret prompt --
        // real multi-step conversations (OTP etc.) would need an
        // interactive follow-up here, not attempted this pass.
        Greetd.respond(root._pendingPw);
        root._pendingPw = "";
      } else if (message) {
        root.msg = { icon: error ? "x" : "info", text: message, color: error ? "#ef596f" : "#5c6370" };
      }
    }
    function onAuthFailure(message) {
      root.busy = false;
      root.msg = { icon: "x", text: message || "authentication failed", color: "#ef596f" };
    }
    function onError(err) {
      root.busy = false;
      root.msg = { icon: "x", text: "greeter backend error: " + err, color: "#ef596f" };
    }
    function onReadyToLaunch() { root.launchRequested(); }
  }

  function doLaunch() {
    const s = sessions[selectedSessionIndex];
    if (mock) {
      console.log("MOCK launch:", s.exec);
      busy = false;
      return;
    }
    // XDG_CURRENT_DESKTOP deliberately left unset -- confirmed live
    // (real hardware) that Hyprland's own startup script sets that one
    // itself and warns "environment seems to be managed externally"
    // when it's already present. Per the XDG spec, XDG_SESSION_DESKTOP
    // is the login-manager-owned variable; XDG_CURRENT_DESKTOP belongs
    // to the desktop environment being launched, not to us.
    //
    // Routed through /bin/sh with stdout/stderr redirected to a log
    // file -- confirmed live (real hardware) that Greetd.launch() execs
    // the command directly with no shell, so once cage exits and hands
    // back the VT, the session script's own startup logging (Hyprland's
    // own, quite verbose) prints straight to the bare text console for
    // the brief moment before Hyprland's compositor takes over and
    // starts actually rendering. Redirecting it keeps that console
    // silent through the handoff.
    Greetd.launch(["/bin/sh", "-c", s.exec.trim() + " >/tmp/qs-greeter-session.log 2>&1"], [
      "XDG_SESSION_TYPE=wayland",
      "XDG_SESSION_DESKTOP=" + s.id,
    ]);
  }

  // Mock auth: "test" succeeds, anything else fails -- mirrors the
  // reference doc's own mock-mode convention.
  Timer {
    id: mockTimer
    interval: 500
    onTriggered: {
      if (root._pendingPw === "test") {
        root._pendingPw = "";
        root.launchRequested();
      } else {
        root._pendingPw = "";
        root.busy = false;
        root.msg = { icon: "x", text: "wrong password (mock: use 'test')", color: "#ef596f" };
      }
    }
  }
}
