# --- Basic setup ---
exec-once = waybar & swayosd-server & hypridle

# --- Background ---
exec-once = swww-daemon && bash -c 'while true; do /home/joelsgc/.coelOS-dotfiles/bin/swww-cycle.sh; sleep 1800; done'

# --- Fingerprint Stuff ---
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# --- Change Power Button Action ---
exec-once = systemd-inhibit --what=handle-power-key --who="Hyprland Menu" --why="Custom Power Menu" --mode=block sleep infinity

# --- Theming ---
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "CoelOS"
exec-once = hyprctl setcursor oreo_spark_light_pink_cursors 32

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# --- Clipboard Storage ---
exec-once = wl-paste --type image --watch clipvault store
exec-once = wl-paste --type text --watch clipvault store
