# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = float 1, match:class com.joelsgc.netpala
windowrule = float 1, match:class com.joelsgc.bluepala
windowrule = float 1, match:class com.joelsgc.floating
windowrule = float 1, size 776 486, match:class com.joelsgc.info

windowrule = center 1, float 1, size 512 768, match:class steam, match:title Friends List
# ---

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
