# ---- Theme Variables ----
# Base:    262626
# Accent:  7acdcd (Cyan)
# Urgent:  ff99da (Pink)

# ---- General ----
timeout: 5
interface_branding: CoelOS Bootloader
interface_branding_color: 1
hash_mismatch_panic: no

# ---- Theme ----
backdrop: 262626
term_background: 262626
term_background_bright: 262626

term_palette: 262626;ff99da;ff99da;df8e1d;1e66f5;ea76cb;179299;7acdcd
term_palette_bright: 262626;ff99da;ff99da;df8e1d;1e66f5;ea76cb;179299;7acdcd

# Global text defaults
term_foreground: 7acdcd
term_foreground_bright: 7acdcd

# ---- Boot Entries ----

/CoelOS
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: cryptdevice=PARTUUID={{ROOT_UUID}}:root root=/dev/mapper/root rw rootfstype=ext4 quiet splash
    module_path: boot():/initramfs-linux.img
